MIN_ZOOM_PERCENT = 25
MAX_ZOOM_PERCENT = 1600
PIPETTE_EDGE_PADDING = 6
AREA_BORDER_HEX = "#dc3737"
SAFE_BORDER_HEX = "#32d25a"
MARKER_HEX = "#ffffff"
TRANSPARENT_KEY = "#010203"
SAMPLE_SIZES = (1, 3, 5, 7)


__all__ = [
    "AREA_BORDER_HEX",
    "MARKER_HEX",
    "MAX_ZOOM_PERCENT",
    "MIN_ZOOM_PERCENT",
    "PIPETTE_EDGE_PADDING",
    "SAFE_BORDER_HEX",
    "SAMPLE_SIZES",
    "TRANSPARENT_KEY",
]
