BANK_AREA = "Bot_Area"

BANK_COLOUR = "cyan"
BANK_MIN_PIXELS = 300
BANK_MAX_PIXELS = 800
BANK_EDGE_PADDING = 20
BANK_BUTTON = "left"

BANK_DEPOSIT_IMAGE = "Bank_Deposit"
BANK_ALL_SELECTED_IMAGE = "BankAllSelected"


__all__ = [
    "BANK_ALL_SELECTED_IMAGE",
    "BANK_AREA",
    "BANK_BUTTON",
    "BANK_COLOUR",
    "BANK_DEPOSIT_IMAGE",
    "BANK_EDGE_PADDING",
    "BANK_MAX_PIXELS",
    "BANK_MIN_PIXELS",
]
