BANK_COLOUR = "cyan"
BANK_AREA = "Bot_Area"
BANK_MIN_PIXELS = 300
BANK_MAX_PIXELS = 800
BANK_EDGE_PADDING = 20
BANK_BUTTON = "left"


__all__ = [
    "BANK_AREA",
    "BANK_BUTTON",
    "BANK_COLOUR",
    "BANK_EDGE_PADDING",
    "BANK_MAX_PIXELS",
    "BANK_MIN_PIXELS",
]
